// uncomment this to turn on all debugging
// #define DEBUG_ALL

// add any new debug macros to this list
#ifdef DEBUG_ALL

#define HCM_DEBUG
#define ENDPOINT_DEBUG
#define ENDPOINT_ZERO_DEBUG
#define ENDPOINT_TEMPERATURE_TARGET_DEBUG
#define ENDPOINT_TEMPERATURE_DEBUG
#define ENDPOINT_ON_OFF_DEBUG
#define ENDPOINT_MOTION_DEBUG
#define ENDPOINT_LEVEL_DEBUG
#define ENDPOINT_IDENTIFY_DEBUG
#define ENDPOINT_COLOR_DEBUG
#define ETHERNET_WRAPPER_DEBUG
#define ESP_WRAPPER_DEBUG
#define ARDUINO_WRAPPER_DEBUG

#endif

// add any new debug macros to this list
// #define HCM_DEBUG
// #define ENDPOINT_DEBUG
// #define ENDPOINT_ZERO_DEBUG
// #define ENDPOINT_TEMPERATURE_TARGET_DEBUG
// #define ENDPOINT_TEMPERATURE_DEBUG
// #define ENDPOINT_ON_OFF_DEBUG
// #define ENDPOINT_MOTION_DEBUG
// #define ENDPOINT_LEVEL_DEBUG
// #define ENDPOINT_IDENTIFY_DEBUG
// #define ENDPOINT_COLOR_DEBUG
// #define ETHERNET_WRAPPER_DEBUG
// #define ESP_WRAPPER_DEBUG
// #define ARDUINO_WRAPPER_DEBUG